import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import * as React from 'react'
import Script from 'next/script'
import ExampleCanvas from '../components/example.js'
import Fotos from './components/fotos.js'
import Jumbo from './components/jumbo'
import Taber from './components/tab.js'
import Slidshow from './components/slidshow.js'
import ProgBar from './components/progbar.js'
import SSRProvider from 'react-bootstrap/SSRProvider'
import {
	Container, Card } from 'react-bootstrap/'



export default function Home() {
  return (<>
      <Head> 
			<title>Development Sinval Gomes Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/logoaondenet.ico" />
      </Head>

		<main>
				<Container>
			  
						<div className="d-flex flex-wrap justify-content-start">
							<div className="card p-3 m3"> 				
								<a href="https://github.com/aondenet-sinval/next-app">
									<h2 className="card-title">Deploy</h2>
								</a>
								<p className="card-text">Essa API &eacute; apenas para treinamento.<br />
								Clicando aqui você irá para o c&oacute;digo fonte.</p>
							</div>
							<div className="card p-3 m-3"> 		
								<a	href="https://github.com/aondenet-sinval">
									<h2 className="card-title">Projetos</h2>
								</a>								
								<p className="card-text">Veja outros projetos.</p>
							</div>
						</div>
						{/*Component fotos*/}
						<Fotos />
						<Jumbo />
						<Slidshow />
						<ProgBar /> 					
						<SSRProvider><Taber /></SSRProvider>
						<ExampleCanvas />
				</Container>	   
		</main>
		</>
  )
}
